define('webview/nls/webview_ja-jp',{
'webview/resources/slreportgen_webview/nls/modelviewer':{"propertyName":"プロパティ名","MarqueeZoomButtonLabel":"ズーム","NoExport":"このシステムはエクスポートされませんでした。","propertyValue":"プロパティ値","ExplorerBarButtonLabel":"エクスプローラー バーの非表示/表示","OpenInNewTab":"新しいタブで開く","blockType":"ブロック タイプ","FitToViewButtonLabel":"ビューに合わせる","ModelBrowserButtonLabel":"モデル ブラウザーの非表示/表示","parent":"親","searchCurrentAndBelow":"現在の階層以下を検索...","searchResults":"検索結果:","name":"名前","advancedSearch":"詳細検索","ViewAll":"すべて表示","Open":"開く","maskType":"マスク タイプ","_localized":{}}
,
'webview/resources/slreportgen_webview/nls/modelbrowser':{"Open":"開く","OpenInNewTab":"新しいタブで開く","Title":"モデル ブラウザー","_localized":{}}
,
'dijit/nls/common':{"buttonOk":"OK","buttonCancel":"キャンセル","buttonSave":"保存","itemClose":"閉じる","_localized":{}}
,
'dijit/nls/loading':{"loadingState":"ロード中...","errorState":"エラーが発生しました。","_localized":{}}
,
'webview/resources/slreportgen_webview/nls/modelinspector':{"Documentation":"ドキュメンテーション","ParameterAttributes":"パラメーター属性","LoggingAndAccessibility":"ログとユーザー補助機能","CodeGeneration":"コード生成","_localized":{}}
,
'webview/resources/slreportgen_webview/nls/utils':{"EdgeLocalFileSupport":"<p>Simulink Web View cannot be viewed in Microsoft Edge because of local file security restrictions. Please use Internet Explorer 11.</p>","SafariLocalFileSupport":"<p>Simulink Web View cannot be viewed in Safari 11+ because of local file security restrictions. To allow local file access:</p> <h4>Enable Develop Menu</h4> <ol> <li>Click on <i>Safari</i> menu. <li>Click on <i>Preferences</i> menu item. <li>Click on <i>Advanced</i> tab.</li> <li>Check <i>Show Develop menu in menu bar</i>.</li> </ol> <h4>Enable local file access</h4> <ol> <li>Click on <i>Develop</i> menu.</li> <li>Select <i>Disable Local File Restrictions.</i></li> <li>Reload page.</li> </ol>","SvgSupport":"<h4>SVG サポートが必要</h4> <p>ブラウザーが Scalable Vector Graphics をサポートしていません。次のいずれかのブラウザーを使用してみてください。 <ul> <li><a href=\"http://www.google.com/chrome/\">Chrome</a></li> <li><a href=\"http://www.mozilla.org/products/firefox/all\">Firefox</a></li> <li><a href=\"http://windows.microsoft.com/en-us/internet-explorer/download-ie\">Internet Explorer 9 以降</a></li> </ul>","UnsupportedBrowser":"サポートされていないブラウザー","ChromeLocalFileSupport":"<p>Simulink の Web ビューは、ローカル ファイルのセキュリティ制限のため Google Chrome では表示できません。ローカル ファイルへのアクセスを可能にするには、以下を試してください。</p> <h4>Microsoft Windows</h4> <ol> <li><b>[スタート]</b> ボタンをクリックして、\"Chrome\" などのブラウザーの実行可能ファイルを検索します。</li> <li>一致したブラウザー検索結果を右クリックして空白の領域にドラッグします。<b>[ショートカットをここに作成]</b> を選択します。</li> <li>新しく作成されたショートカットを右クリックして <b>[プロパティ]</b> を選択します。</li> <li><b>[ショートカット]</b> タブをクリックします。</li> <li>ターゲットのエディット ボックスで、\"--allow-file-access-from-files\" を引用符なしで追加します。</li> <li><b>[OK]</b> をクリックしてプロパティ ダイアログ ボックスを閉じます。</li> <li>ブラウザーが実行されていないことを確認します。</li> <li>新しく作成されたショートカットをダブルクリックしてブラウザーを起動します。</li> </ol> <h4>Mac</h4> <ol> <li>Terminal.app を実行します。</li> <li>\"open /Applications Google Chrome.app --allow-file-access-from-files\" を引用符なしで入力します。</li> </ol> <h4>Linux</h4> <ol> <li>ターミナルを起動します。</li> <li>\"./chromium-browser --allow-file-access-from-files\" を引用符なしで入力します。</li> </ol>","OtherLocalFileSupport":"<p>Simulink Web View cannot be viewed because of local file security restrictions. Please enable local file access.</p>","_localized":{}}
});