set MATLAB=F:\matlab\install
"%MATLAB%\bin\%MATLAB_WIN_VER%\gmake" -f moving.mk  GENERATE_ASAP2=0 DOWNLOADAPPLICATION=1 STM32CUBEMXPATHUPDATE=1 STM32CUBEMXPATH="E:\stm32_hal\install" TARGET_INST_FULLPATH="E:\MATLAB\STM32-MAT\STM32" IOC_FULLPATH="C:\Users\zqx\Desktop\encoder\mat_motor\move\move.ioc" IT_HANDLER_OPTIM=1 ISPROTECTINGMODEL=NOTPROTECTING
