define('webview/nls/webview_es-es',{
'webview/resources/slreportgen_webview/nls/modelviewer':{"propertyName":"Property Name","MarqueeZoomButtonLabel":"Zoom","NoExport":"This system was not exported.","propertyValue":"Property Value","ExplorerBarButtonLabel":"Hide/Show Explorer Bar","OpenInNewTab":"Open In New Tab","blockType":"Block Type","FitToViewButtonLabel":"Fit to View","ModelBrowserButtonLabel":"Hide/Show Model Browser","parent":"Parent","searchCurrentAndBelow":"Search current and below...","searchResults":"Search Results:","name":"Name","advancedSearch":"Advanced Search","ViewAll":"View All","Open":"Open","maskType":"Mask Type","_localized":{}}
,
'webview/resources/slreportgen_webview/nls/modelbrowser':{"Open":"Open","OpenInNewTab":"Open In New Tab","Title":"Model Browser","_localized":{}}
,
'dijit/nls/common':{"buttonOk":"Aceptar","buttonCancel":"Cancelar","buttonSave":"Guardar","itemClose":"Cerrar","_localized":{}}
,
'dijit/nls/loading':{"loadingState":"Cargando...","errorState":"Lo siento, se ha producido un error","_localized":{}}
,
'webview/resources/slreportgen_webview/nls/modelinspector':{"Documentation":"Documentation","ParameterAttributes":"Parameter Attributes","LoggingAndAccessibility":"Logging and Accessibility","CodeGeneration":"Code Generation","_localized":{}}
,
'webview/resources/slreportgen_webview/nls/utils':{"EdgeLocalFileSupport":"<p>Simulink Web View cannot be viewed in Microsoft Edge because of local file security restrictions. Please use Internet Explorer 11.</p>","SafariLocalFileSupport":"<p>Simulink Web View cannot be viewed in Safari 11+ because of local file security restrictions. To allow local file access:</p> <h4>Enable Develop Menu</h4> <ol> <li>Click on <i>Safari</i> menu. <li>Click on <i>Preferences</i> menu item. <li>Click on <i>Advanced</i> tab.</li> <li>Check <i>Show Develop menu in menu bar</i>.</li> </ol> <h4>Enable local file access</h4> <ol> <li>Click on <i>Develop</i> menu.</li> <li>Select <i>Disable Local File Restrictions.</i></li> <li>Reload page.</li> </ol>","SvgSupport":"<h4>SVG Support Required</h4> <p>Your browser does not support Scalable Vector Graphics.  Try to use one of the following browser: <ul> <li><a href=\"http://www.google.com/chrome/\">Chrome</a></li> <li><a href=\"http://www.mozilla.org/products/firefox/all\">Firefox</a></li> <li><a href=\"http://windows.microsoft.com/en-us/internet-explorer/download-ie\">Internet Explorer 9 or later</a></li> </ul>","UnsupportedBrowser":"Unsupported Browser","ChromeLocalFileSupport":"<p>Simulink Web View cannot be viewed in Google Chrome because of local file security restrictions. To allow local file access, try the following:</p> <h4>Microsoft Windows</h4> <ol> <li>Click the <b>Start</b> button and search for the browser executable,  such as \"Chrome\".</li> <li>Right-click and drag the matched browser search result to an open area. Select <b>Create shortcuts here</b>.</li> <li>Right-click the newly created shortcut and select <b>Properties</b>.</li> <li>Click the <b>Shortcut</b> tab.</li> <li>In the target edit box, append \"--allow-file-access-from-files\", with no quotes.</li> <li>Click <b>OK</b> to dismiss property dialog box.</li> <li>Verify that the browser is no longer running.</li> <li>Double-click on the newly created shortcut to start the browser.</li> </ol> <h4>Mac</h4> <ol> <li>Run Terminal.app.</li> <li>Type \"open /Applications Google Chrome.app --allow-file-access-from-files\", with no quotes.</li> </ol> <h4>Linux</h4> <ol> <li>Start terminal.</li> <li>Type \"./chromium-browser --allow-file-access-from-files\", with no quotes.</li> </ol>","OtherLocalFileSupport":"<p>Simulink Web View cannot be viewed because of local file security restrictions. Please enable local file access.</p>","_localized":{}}
});